backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "source/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


locale: "en"

collections:
  - name: "post"
    label: "Post"
    folder: "source/_posts"
    # filter:
    #   field: language
    #   value: en
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" } # 隐藏字段，用于 Hexo 布局
      #post description
      - { label: "Title", name: "title", widget: "string", required: true}
      - { label: "Publish Date", name: "date", widget: "datetime",format: "YYYY-MM-DD HH:mm:ss +0800" }
      - { label: "Updated", name: "updated", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss +0800", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      #post image
      - { label: "Cover", name: "cover", widget: "image", required: false } # 新增：文章列表的封面图
      - { label: "Top_img", name: "top_img", widget: "image", required: false } # 新增：文章顶部的图片
      #post categories
      - { label: "Categories", name: "categories", widget: "list", allow_add: true, required: false } # 新增
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, required: false } # 新增
      #post display menu
      - { label: "Aside", name: "aside", widget: "boolean", default: true, required: false } # 新增
      - { label: "Comments", name: "comments", widget: "boolean", default: true, required: false } # 新增
      - { label: "Toc", name: "toc", widget: "boolean", default: true, required: false } # 新增
      - { label: "Toc_number", name: "toc_number", widget: "boolean", default: true, required: false } # 新增
      - { label: "Toc_style_simple", name: "toc_style_simple", widget: "boolean", default: false, required: false } # 新增
      #Decap Cms
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number", required: false }

